export const endpoints = {
  adminLogin: "/admin/login",
  jobs: "/api/hr/jobs",
  job: (jobId) => `/api/hr/jobs/${encodeURIComponent(jobId)}`,
  jobApplications: (jobId) => `/api/hr/jobs/${encodeURIComponent(jobId)}/applications`,
  jobRecords: (jobId) => `/api/hr/jobs/${encodeURIComponent(jobId)}/records`,
  quickSelect: (jobId) => `/api/hr/jobs/${encodeURIComponent(jobId)}/quick-select`,
  application: (applicationId) => `/api/hr/applications/${encodeURIComponent(applicationId)}`,
  applicationDecision: (applicationId) => `/api/hr/applications/${encodeURIComponent(applicationId)}/hr-decision`,
  resumeUpload: "/api/resume/upload",
  resumeBulkUpload: "/api/resume/bulk-upload",
  resumeDownload: (applicationId) => `/api/hr/applications/${encodeURIComponent(applicationId)}/resume/download`,
  resumeView: (applicationId) => `/api/hr/applications/${encodeURIComponent(applicationId)}/resume/view`,
  atsScore: (applicationId) => `/api/ats/score/${encodeURIComponent(applicationId)}`,
  atsDecision: (applicationId) => `/api/ats/${encodeURIComponent(applicationId)}/decision`,
  questionBank: (jobId) => `/api/hr/jobs/${encodeURIComponent(jobId)}/question-bank`,
  questionBankSave: "/api/hr/question-bank/questions",
  questionBankParseUpload: "/api/hr/question-bank/parse-upload",
  questionBankQuestion: (questionId) => `/api/hr/question-bank/questions/${encodeURIComponent(questionId)}`,
  questionBankClear: (jobId) => `/api/hr/question-bank?job_id=${encodeURIComponent(jobId)}`,
  configureData: (applicationId) => `/api/interviews/${encodeURIComponent(applicationId)}/configure-data`,
  configureQuestions: (applicationId) => `/api/interviews/${encodeURIComponent(applicationId)}/configure-questions`,
  createInterviewLink: "/api/interview/create-link",
  interviewAccess: (applicationId) => `/api/interviews/${encodeURIComponent(applicationId)}/access-status`,
  interviewHeartbeat: (applicationId) => `/api/interviews/${encodeURIComponent(applicationId)}/heartbeat`,
  interviewQuit: (applicationId) => `/api/interviews/${encodeURIComponent(applicationId)}/quit`,
  interviewQuestions: (applicationId) => `/api/interview/${encodeURIComponent(applicationId)}/questions`,
  interviewRegenerate: (applicationId) => `/api/interview/questions/${encodeURIComponent(applicationId)}/regenerate`,
  interviewTranscribe: (applicationId) => `/api/interview/${encodeURIComponent(applicationId)}/transcribe`,
  interviewStart: (applicationId) => `/api/interview/${encodeURIComponent(applicationId)}/start`,
  interviewEvaluate: (applicationId) => `/api/interview/questions/${encodeURIComponent(applicationId)}/evaluate`,
  interviewComplete: (applicationId) => `/api/interview/questions/${encodeURIComponent(applicationId)}/complete`,
  interviewSaveAnswer: (applicationId) => `/api/interviews/${encodeURIComponent(applicationId)}/answers/save`,
  livenessReference: (applicationId) => `/api/interviews/${encodeURIComponent(applicationId)}/liveness/reference`,
  livenessCheck: (applicationId) => `/api/interviews/${encodeURIComponent(applicationId)}/liveness/check`,
  interviewToken: (token) => `/api/interview/validate-token/${encodeURIComponent(token)}`,
  qwenHealth: "/api/interview/qwen-health",
  faceVerify: (applicationId) => `/api/interview/face-verify/${encodeURIComponent(applicationId)}`,
  identityUpload: (applicationId) => `/api/kyc/identity/upload/${encodeURIComponent(applicationId)}`,
  candidateVerification: (applicationId) => `/api/kyc/candidate/${encodeURIComponent(applicationId)}`,
  verificationStatus: (applicationId) => `/api/kyc/verification-status/${encodeURIComponent(applicationId)}`,
  markVerified: (applicationId) => `/api/kyc/verification/mark/${encodeURIComponent(applicationId)}`,
  candidateReport: (applicationId) => `/api/hr/applications/${encodeURIComponent(applicationId)}/report`,
  reports: "/api/hr/reports",
};
